const fs = require('fs');
const path = require('path');
const bcrypt = require('bcryptjs');
const { PDFDocument, StandardFonts, rgb } = require('pdf-lib');
const env = require('./config/env');
const {
  sequelize,
  Company,
  User,
  CompanyDocument,
  MasterChecklistItem,
  Project,
  ChildChecklist,
  ChildChecklistItem,
  AlertSetting
} = require('./models');

const checklistItems = [
  ['Table of Contents', 'YES', ''],
  ['Scope of Works', '', 'As per BOQ'],
  ['Manufacturer/Supplier profile/portfolio with Organization chart showing the QA/QC Department structure', 'YES', ''],
  ['AVL Availability', 'YES', ''],
  ['Supplier Authorization Letter', 'YES', ''],
  ['Supplier Commercial Registration Documents Copy of valid commercial license & certificate and Company ID', 'YES', ''],
  ['Compliance with Project Specification', 'NA', 'REFER TO QCS COMPLIANCE'],
  ['Compliance with Project QCS 2014', 'YES', ''],
  ['Copy of valid certificate/approval of the firm from concerned governmental departments/agencies, such as MME', 'YES', ''],
  ['Material List/Schedule', 'YES', ''],
  ['Material Datasheets/Selection', 'YES', ''],
  ['Original copy of brochure/catalogue of each proposed material', 'YES', ''],
  ['Required Calculations', 'YES', ''],
  ['Required Drawings', 'NA', ''],
  ['Proposed location of Installation', 'As Required', ''],
  ['Third-Party Certificates/Report', 'YES', ''],
  ['Manufacturer Installation Instructions', 'YES', ''],
  ['Conformity Certificates', 'YES', ''],
  ['Material Country of Origin', 'YES', ''],
  ['Updated list of previous/current projects with completion certificates and approvals', 'YES', ''],
  ['Management Systems Certification such as QMS ISO 9001, EMS ISO 14001, OHSAS 18001/ISO 45001', 'YES', ''],
  ['Warranty Letter Draft', 'YES', ''],
  ['Test Reports', 'YES', ''],
  ['Physical samples with manufacturer details and country permanently marked as per specification', 'NA', 'Will be provided as part of material approval'],
  ['Copy of the required guarantee mentioned in the contract document', 'NA', '']
];

const createSamplePdf = async (filePath, title) => {
  const doc = await PDFDocument.create();
  const page = doc.addPage([595, 842]);
  const regular = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);
  page.drawRectangle({ x: 0, y: 730, width: 595, height: 112, color: rgb(0.03, 0.24, 0.45) });
  page.drawText(title, { x: 48, y: 775, size: 24, font: bold, color: rgb(1, 1, 1) });
  page.drawText('Sample supporting document generated by the demo seed.', { x: 48, y: 670, size: 12, font: regular });
  page.drawText('Replace this file with the client-approved legal or technical document.', { x: 48, y: 642, size: 11, font: regular });
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, await doc.save());
};

const run = async () => {
  await sequelize.authenticate();
  await sequelize.sync({ force: true });
  fs.mkdirSync(env.uploadRoot, { recursive: true });

  const passwordHash = await bcrypt.hash('Admin@123', 12);
  const staffHash = await bcrypt.hash('Staff@123', 12);

  const company = await Company.create({
    name: 'ABC Construction W.L.L.',
    crNumber: 'QCR-1002456',
    address: 'King Fahad Road, Al Olaya, Doha, Qatar',
    contactPerson: 'John Doe',
    email: 'info@abcconstruction.local',
    phone: '+974 5555 1234',
    settings: { defaultStatuses: ['YES', 'NO', 'NA', 'UNDER REVIEW', 'APPROVED', 'NOT SUBMITTED'] }
  });

  await AlertSetting.create({ companyId: company.id, daysBefore: [30, 15, 7], recipientEmails: 'admin@abc.local', frequency: 'DAILY', enabled: true });

  await User.bulkCreate([
    { name: 'System Administrator', email: 'superadmin@pqd.local', passwordHash, role: 'SUPER_ADMIN', companyId: null },
    { name: 'ABC Company Admin', email: 'admin@abc.local', passwordHash, role: 'COMPANY_ADMIN', companyId: company.id },
    { name: 'ABC Staff User', email: 'staff@abc.local', passwordHash: staffHash, role: 'STAFF', companyId: company.id }
  ]);

  const master = await MasterChecklistItem.bulkCreate(checklistItems.map(([title, defaultStatus, defaultRemark], index) => ({
    companyId: company.id,
    title,
    defaultStatus,
    defaultRemark,
    sortOrder: index + 1,
    isActive: true
  })));

  const project = await Project.create({
    companyId: company.id,
    name: 'Metro Station Expansion',
    number: 'MSE-2026-014',
    client: 'Public Works Authority',
    consultant: 'Global Engineering Consultants',
    contractor: 'Main Contractor W.L.L.',
    supplier: company.name,
    productSystem: 'HVAC Equipment and Accessories',
    revision: '0',
    projectDate: new Date().toISOString().slice(0, 10),
    submittalNumber: 'PQD-HVAC-001',
    discipline: 'Mechanical'
  });

  const child = await ChildChecklist.create({ companyId: company.id, projectId: project.id, name: 'Main Contractor PQD', description: 'Initial HVAC prequalification checklist.' });
  await ChildChecklistItem.bulkCreate(master.slice(0, 12).map((item, index) => ({
    childChecklistId: child.id,
    masterItemId: item.id,
    titleSnapshot: item.title,
    status: item.defaultStatus,
    remarks: item.defaultRemark,
    sortOrder: index + 1
  })));

  const docsDir = path.join(env.uploadRoot, 'documents', company.id);
  const activeFile = path.join(docsDir, 'sample-company-profile.pdf');
  const expiringFile = path.join(docsDir, 'sample-iso-certificate.pdf');
  const expiredFile = path.join(docsDir, 'sample-commercial-registration.pdf');
  await createSamplePdf(activeFile, 'Company Profile');
  await createSamplePdf(expiringFile, 'ISO 9001 Certificate');
  await createSamplePdf(expiredFile, 'Commercial Registration');

  const admin = await User.findOne({ where: { email: 'admin@abc.local' } });
  const today = new Date();
  const plusDays = (days) => { const date = new Date(today); date.setDate(date.getDate() + days); return date.toISOString().slice(0, 10); };
  await CompanyDocument.bulkCreate([
    { companyId: company.id, createdById: admin.id, title: 'Company Profile and Portfolio', category: 'Company Documents', expiryDate: plusDays(365), documentType: 'Profile', filePath: activeFile, originalName: 'company-profile.pdf', mimeType: 'application/pdf', sizeBytes: fs.statSync(activeFile).size },
    { companyId: company.id, createdById: admin.id, title: 'ISO 9001 Certificate', category: 'Certificates', expiryDate: plusDays(18), documentType: 'Certificate', filePath: expiringFile, originalName: 'iso-9001-certificate.pdf', mimeType: 'application/pdf', sizeBytes: fs.statSync(expiringFile).size },
    { companyId: company.id, createdById: admin.id, title: 'Commercial Registration', category: 'Legal Documents', expiryDate: plusDays(-10), documentType: 'Legal', filePath: expiredFile, originalName: 'commercial-registration.pdf', mimeType: 'application/pdf', sizeBytes: fs.statSync(expiredFile).size }
  ]);

  console.log('Database seeded successfully.');
  console.log('Super Admin: superadmin@pqd.local / Admin@123');
  console.log('Company Admin: admin@abc.local / Admin@123');
  console.log('Staff: staff@abc.local / Staff@123');
  await sequelize.close();
};

run().catch(async (error) => {
  console.error(error);
  await sequelize.close();
  process.exit(1);
});
